// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package io.netty.example.codec.person;

import com.google.protobuf.Descriptors;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.GeneratedMessage;

public final class PersonProbuf {
	private PersonProbuf() {
	}

	public static void registerAllExtensions(ExtensionRegistry registry) {
	}

	static final Descriptors.Descriptor internal_static_Person_descriptor;
	
	static GeneratedMessage.FieldAccessorTable internal_static_Person_fieldAccessorTable;
	
	static final Descriptors.Descriptor internal_static_Person_PhoneNumber_descriptor;
	
	static GeneratedMessage.FieldAccessorTable internal_static_Person_PhoneNumber_fieldAccessorTable;
	
	static final Descriptors.Descriptor internal_static_Person_CountryInfo_descriptor;
	
	static GeneratedMessage.FieldAccessorTable internal_static_Person_CountryInfo_fieldAccessorTable;
	
	static final Descriptors.Descriptor internal_static_AddressBook_descriptor;
	
	static GeneratedMessage.FieldAccessorTable internal_static_AddressBook_fieldAccessorTable;

	public static Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static Descriptors.FileDescriptor descriptor;
	
	static {
		java.lang.String[] descriptorData = { "\n\tmsg.proto\"\203\002\n\006Person\022\014\n\004name\030\001 \002(\t\022\n\n\002" + "id\030\002 \002(\005\022\r\n\005email\030\003 \001(\t\022\"\n\005phone\030\004 \003(\0132\023" + ".Person.PhoneNumber\032D\n\013PhoneNumber\022\016\n\006nu"
				+ "mber\030\001 \002(\t\022%\n\004type\030\002 \001(\0162\021.Person.PhoneT" + "ype:\004HOME\0329\n\013CountryInfo\022\014\n\004name\030\001 \002(\t\022\014" + "\n\004code\030\002 \002(\t\022\016\n\006number\030\003 \001(\005\"+\n\tPhoneTyp"
				+ "e\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"&\n\013Add" + "ressBook\022\027\n\006person\030\001 \003(\0132\007.PersonB&\n\026io." + "netty.example.codecB\014PersonProbuf" };
		Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public ExtensionRegistry assignDescriptors(Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		
		Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new Descriptors.FileDescriptor[] {}, assigner);
		
		internal_static_Person_descriptor = getDescriptor().getMessageTypes().get(0);
		
		internal_static_Person_fieldAccessorTable = new GeneratedMessage.FieldAccessorTable(internal_static_Person_descriptor, new java.lang.String[] { "Name", "Id", "Email", "Phone", });
		
		internal_static_Person_PhoneNumber_descriptor = internal_static_Person_descriptor.getNestedTypes().get(0);
		
		internal_static_Person_PhoneNumber_fieldAccessorTable = new GeneratedMessage.FieldAccessorTable(internal_static_Person_PhoneNumber_descriptor, new java.lang.String[] { "Number", "Type", });
		
		internal_static_Person_CountryInfo_descriptor = internal_static_Person_descriptor.getNestedTypes().get(1);
		
		internal_static_Person_CountryInfo_fieldAccessorTable = new GeneratedMessage.FieldAccessorTable(internal_static_Person_CountryInfo_descriptor, new java.lang.String[] { "Name", "Code", "Number", });
		
		internal_static_AddressBook_descriptor = getDescriptor().getMessageTypes().get(1);
		
		internal_static_AddressBook_fieldAccessorTable = new GeneratedMessage.FieldAccessorTable(internal_static_AddressBook_descriptor, new java.lang.String[] { "Person", });
	}


}
